/**
 * Rule-seed entries: merchant-specific keywords migrated out of classifier.ts.
 *
 * Each entry maps a normalized merchantKey (the value produced by
 * `recurrenceKey(normalizeMerchant(rawDescription))` for clean bank descriptions)
 * to the classification that would have been produced by the keyword rule.
 *
 * These are seeded into `merchant_classifications` with source="rule-seed" and
 * onConflictDoNothing, so they never overwrite existing manual or AI entries.
 * Coverage: clean descriptions where the bank sends exactly the merchant name.
 * Noisy variants (e.g. "NETFLIX.COM") still fall to AI on first encounter and
 * then are cached normally.
 */

export type RuleSeedEntry = {
  merchantKeyPattern: string;
  category: string;
  transactionClass: "expense" | "income" | "transfer" | "refund";
  recurrenceType: "recurring" | "one-time";
  confidence: number;
};

function e(
  merchantKeyPattern: string,
  category: string,
  transactionClass: "expense" | "income" | "transfer" | "refund",
  recurrenceType: "recurring" | "one-time",
  confidence: number,
): RuleSeedEntry {
  return { merchantKeyPattern: merchantKeyPattern.trim().toLowerCase(), category, transactionClass, recurrenceType, confidence };
}

// ─── Debt — specific lenders ──────────────────────────────────────────────────
const DEBT_ENTRIES: RuleSeedEntry[] = [
  // Student loan servicers
  e("sallie mae", "debt", "expense", "recurring", 0.92),
  e("navient", "debt", "expense", "recurring", 0.92),
  e("great lakes", "debt", "expense", "recurring", 0.92),
  e("fedloan", "debt", "expense", "recurring", 0.92),
  e("mohela", "debt", "expense", "recurring", 0.92),
  e("nelnet", "debt", "expense", "recurring", 0.92),
  e("aidvantage", "debt", "expense", "recurring", 0.92),
  e("edfinancial", "debt", "expense", "recurring", 0.92),
  e("discover student", "debt", "expense", "recurring", 0.92),
  // Personal loan providers
  e("sofi loan", "debt", "expense", "recurring", 0.92),
  e("earnest loan", "debt", "expense", "recurring", 0.92),
  e("upstart", "debt", "expense", "recurring", 0.92),
  e("upstloantr", "debt", "expense", "recurring", 0.92),
  // Credit card issuers (payment entries)
  e("payment to chase", "debt", "expense", "recurring", 0.92),
  e("payment to comenity", "debt", "expense", "recurring", 0.92),
  e("payment to citibank", "debt", "expense", "recurring", 0.92),
  e("payment to capital one", "debt", "expense", "recurring", 0.92),
  e("payment to american express", "debt", "expense", "recurring", 0.92),
  e("payment to discover", "debt", "expense", "recurring", 0.92),
  e("payment to synchrony", "debt", "expense", "recurring", 0.92),
  e("payment to barclays", "debt", "expense", "recurring", 0.92),
  e("payment to ally", "debt", "expense", "recurring", 0.92),
  e("payment to bank of america", "debt", "expense", "recurring", 0.92),
  e("payment to wells fargo", "debt", "expense", "recurring", 0.92),
];

// ─── Insurance — specific carriers ───────────────────────────────────────────
const INSURANCE_ENTRIES: RuleSeedEntry[] = [
  e("geico", "insurance", "expense", "recurring", 0.9),
  e("state farm", "insurance", "expense", "recurring", 0.9),
  e("allstate", "insurance", "expense", "recurring", 0.9),
  e("progressive", "insurance", "expense", "recurring", 0.9),
  e("liberty mutual", "insurance", "expense", "recurring", 0.9),
  e("usaa", "insurance", "expense", "recurring", 0.9),
  e("nationwide", "insurance", "expense", "recurring", 0.9),
  e("farmers", "insurance", "expense", "recurring", 0.9),
  e("metlife", "insurance", "expense", "recurring", 0.9),
  e("aetna", "insurance", "expense", "recurring", 0.9),
  e("cigna", "insurance", "expense", "recurring", 0.9),
  e("blue cross", "insurance", "expense", "recurring", 0.9),
  e("bluecross", "insurance", "expense", "recurring", 0.9),
  e("anthem", "insurance", "expense", "recurring", 0.9),
  e("united health", "insurance", "expense", "recurring", 0.9),
  e("unitedhealthcare", "insurance", "expense", "recurring", 0.9),
  e("humana", "insurance", "expense", "recurring", 0.9),
  e("oscar health", "insurance", "expense", "recurring", 0.9),
  e("kaiser permanente", "insurance", "expense", "recurring", 0.9),
  e("hartford insurance", "insurance", "expense", "recurring", 0.9),
  e("travelers insurance", "insurance", "expense", "recurring", 0.9),
  e("chubb", "insurance", "expense", "recurring", 0.9),
  e("erie insurance", "insurance", "expense", "recurring", 0.9),
  e("lemonade insurance", "insurance", "expense", "recurring", 0.9),
  e("root insurance", "insurance", "expense", "recurring", 0.9),
  e("hippo insurance", "insurance", "expense", "recurring", 0.9),
  e("esurance", "insurance", "expense", "recurring", 0.9),
  e("21st century insurance", "insurance", "expense", "recurring", 0.9),
  e("safeco", "insurance", "expense", "recurring", 0.9),
];

// ─── Entertainment — streaming services ──────────────────────────────────────
const STREAMING_ENTRIES: RuleSeedEntry[] = [
  e("netflix", "entertainment", "expense", "recurring", 0.9),
  e("hulu", "entertainment", "expense", "recurring", 0.9),
  e("disney+", "entertainment", "expense", "recurring", 0.9),
  e("disney plus", "entertainment", "expense", "recurring", 0.9),
  e("disneyplus", "entertainment", "expense", "recurring", 0.9),
  e("hbo max", "entertainment", "expense", "recurring", 0.9),
  e("max.com", "entertainment", "expense", "recurring", 0.9),
  e("paramount+", "entertainment", "expense", "recurring", 0.9),
  e("paramount plus", "entertainment", "expense", "recurring", 0.9),
  e("peacock", "entertainment", "expense", "recurring", 0.9),
  e("peacocktv", "entertainment", "expense", "recurring", 0.9),
  e("crunchyroll", "entertainment", "expense", "recurring", 0.9),
  e("funimation", "entertainment", "expense", "recurring", 0.9),
  e("mubi", "entertainment", "expense", "recurring", 0.9),
  e("criterion", "entertainment", "expense", "recurring", 0.9),
  e("discovery+", "entertainment", "expense", "recurring", 0.9),
  e("espn+", "entertainment", "expense", "recurring", 0.9),
  e("fubo", "entertainment", "expense", "recurring", 0.9),
  e("philo", "entertainment", "expense", "recurring", 0.9),
  e("sling tv", "entertainment", "expense", "recurring", 0.9),
  e("directv stream", "entertainment", "expense", "recurring", 0.9),
  e("xbox game pass", "entertainment", "expense", "recurring", 0.9),
  e("playstation plus", "entertainment", "expense", "recurring", 0.9),
  e("nintendo switch online", "entertainment", "expense", "recurring", 0.9),
  e("twitch", "entertainment", "expense", "recurring", 0.9),
  e("substack", "entertainment", "expense", "recurring", 0.9),
  e("patreon", "entertainment", "expense", "recurring", 0.9),
  e("onlyfans", "entertainment", "expense", "recurring", 0.9),
];

// ─── Software — consumer subscriptions ───────────────────────────────────────
const SOFTWARE_CONSUMER_ENTRIES: RuleSeedEntry[] = [
  e("spotify", "software", "expense", "recurring", 0.9),
  e("apple music", "software", "expense", "recurring", 0.9),
  e("apple tv", "software", "expense", "recurring", 0.9),
  e("apple one", "software", "expense", "recurring", 0.9),
  e("youtube premium", "software", "expense", "recurring", 0.9),
  e("youtube music", "software", "expense", "recurring", 0.9),
  e("amazon music", "software", "expense", "recurring", 0.9),
  e("siriusxm", "software", "expense", "recurring", 0.9),
  e("pandora", "software", "expense", "recurring", 0.9),
  e("tidal", "software", "expense", "recurring", 0.9),
  e("deezer", "software", "expense", "recurring", 0.9),
  e("audible", "software", "expense", "recurring", 0.9),
  e("kindle unlimited", "software", "expense", "recurring", 0.9),
  e("amazon prime", "software", "expense", "recurring", 0.9),
  e("icloud", "software", "expense", "recurring", 0.9),
  e("google one", "software", "expense", "recurring", 0.9),
  e("google storage", "software", "expense", "recurring", 0.9),
  e("microsoft 365", "software", "expense", "recurring", 0.9),
  e("office 365", "software", "expense", "recurring", 0.9),
  e("masterclass", "software", "expense", "recurring", 0.9),
  e("chatgpt", "software", "expense", "recurring", 0.9),
  e("openai", "software", "expense", "recurring", 0.9),
  e("claude ai", "software", "expense", "recurring", 0.9),
  e("claude.ai", "software", "expense", "recurring", 0.9),
  e("anthropic", "software", "expense", "recurring", 0.9),
  e("elevenlabs", "software", "expense", "recurring", 0.9),
  e("midjourney", "software", "expense", "recurring", 0.9),
  e("runway ml", "software", "expense", "recurring", 0.9),
  e("adobe", "software", "expense", "recurring", 0.9),
  e("figma", "software", "expense", "recurring", 0.9),
  e("notion", "software", "expense", "recurring", 0.9),
  e("airtable", "software", "expense", "recurring", 0.9),
  e("monday.com", "software", "expense", "recurring", 0.9),
  e("asana", "software", "expense", "recurring", 0.9),
  e("slack", "software", "expense", "recurring", 0.9),
  e("zoom.us", "software", "expense", "recurring", 0.9),
  e("dropbox", "software", "expense", "recurring", 0.9),
  e("box.com", "software", "expense", "recurring", 0.9),
  e("1password", "software", "expense", "recurring", 0.9),
  e("lastpass", "software", "expense", "recurring", 0.9),
  e("nordvpn", "software", "expense", "recurring", 0.9),
  e("expressvpn", "software", "expense", "recurring", 0.9),
  e("malwarebytes", "software", "expense", "recurring", 0.9),
  e("mcafee", "software", "expense", "recurring", 0.9),
  e("norton", "software", "expense", "recurring", 0.9),
  e("grammarly", "software", "expense", "recurring", 0.9),
  e("canva", "software", "expense", "recurring", 0.9),
  e("replit", "software", "expense", "recurring", 0.9),
  e("paddle net", "software", "expense", "recurring", 0.9),
  e("paddle.com", "software", "expense", "recurring", 0.9),
  e("2cocom", "software", "expense", "recurring", 0.9),
  e("2checkout", "software", "expense", "recurring", 0.9),
];

// ─── Software — business / SaaS ───────────────────────────────────────────────
const SOFTWARE_BUSINESS_ENTRIES: RuleSeedEntry[] = [
  e("github", "software", "expense", "recurring", 0.85),
  e("gitlab", "software", "expense", "recurring", 0.85),
  e("heroku", "software", "expense", "recurring", 0.85),
  e("aws", "software", "expense", "recurring", 0.85),
  e("amazon web services", "software", "expense", "recurring", 0.85),
  e("google cloud", "software", "expense", "recurring", 0.85),
  e("gcp", "software", "expense", "recurring", 0.85),
  e("azure", "software", "expense", "recurring", 0.85),
  e("digitalocean", "software", "expense", "recurring", 0.85),
  e("vercel", "software", "expense", "recurring", 0.85),
  e("netlify", "software", "expense", "recurring", 0.85),
  e("render.com", "software", "expense", "recurring", 0.85),
  e("railway", "software", "expense", "recurring", 0.85),
  e("fly.io", "software", "expense", "recurring", 0.85),
  e("supabase", "software", "expense", "recurring", 0.85),
  e("planetscale", "software", "expense", "recurring", 0.85),
  e("neon.tech", "software", "expense", "recurring", 0.85),
  e("zoom", "software", "expense", "recurring", 0.85),
  e("jira", "software", "expense", "recurring", 0.85),
  e("atlassian", "software", "expense", "recurring", 0.85),
  e("confluence", "software", "expense", "recurring", 0.85),
  e("trello", "software", "expense", "recurring", 0.85),
  e("clickup", "software", "expense", "recurring", 0.85),
  e("linear.app", "software", "expense", "recurring", 0.85),
  e("basecamp", "software", "expense", "recurring", 0.85),
  e("quickbooks", "software", "expense", "recurring", 0.85),
  e("freshbooks", "software", "expense", "recurring", 0.85),
  e("xero", "software", "expense", "recurring", 0.85),
  e("wave accounting", "software", "expense", "recurring", 0.85),
  e("bench accounting", "software", "expense", "recurring", 0.85),
  e("mailchimp", "software", "expense", "recurring", 0.85),
  e("sendgrid", "software", "expense", "recurring", 0.85),
  e("hubspot", "software", "expense", "recurring", 0.85),
  e("salesforce", "software", "expense", "recurring", 0.85),
  e("zendesk", "software", "expense", "recurring", 0.85),
  e("intercom", "software", "expense", "recurring", 0.85),
  e("squarespace", "software", "expense", "recurring", 0.85),
  e("shopify", "software", "expense", "recurring", 0.85),
  e("wix", "software", "expense", "recurring", 0.85),
  e("webflow", "software", "expense", "recurring", 0.85),
  e("godaddy", "software", "expense", "recurring", 0.85),
  e("namecheap", "software", "expense", "recurring", 0.85),
  e("cloudflare", "software", "expense", "recurring", 0.85),
  e("twilio", "software", "expense", "recurring", 0.85),
  e("stripe", "software", "expense", "recurring", 0.85),
  e("plaid", "software", "expense", "recurring", 0.85),
  e("docusign", "software", "expense", "recurring", 0.85),
  e("hellosign", "software", "expense", "recurring", 0.85),
  e("adobe acrobat", "software", "expense", "recurring", 0.85),
  e("adobe creative", "software", "expense", "recurring", 0.85),
  e("adobe sign", "software", "expense", "recurring", 0.85),
  e("loom", "software", "expense", "recurring", 0.85),
  e("calendly", "software", "expense", "recurring", 0.85),
  e("doodle", "software", "expense", "recurring", 0.85),
  e("dashlane", "software", "expense", "recurring", 0.85),
  e("gusto", "software", "expense", "recurring", 0.85),
  e("rippling", "software", "expense", "recurring", 0.85),
  e("deel", "software", "expense", "recurring", 0.85),
  e("remote.com", "software", "expense", "recurring", 0.85),
  e("bamboohr", "software", "expense", "recurring", 0.85),
  e("workday", "software", "expense", "recurring", 0.85),
  e("greenhouse", "software", "expense", "recurring", 0.85),
  e("lever.co", "software", "expense", "recurring", 0.85),
  e("dropbox business", "software", "expense", "recurring", 0.85),
  e("microsoft", "software", "expense", "recurring", 0.85),
  e("apple.com", "software", "expense", "recurring", 0.85),
  e("apple store", "software", "expense", "recurring", 0.85),
  e("discord", "software", "expense", "recurring", 0.85),
  e("x corp", "software", "expense", "recurring", 0.85),
  e("twitter paid", "software", "expense", "recurring", 0.85),
  e("twitter subscription", "software", "expense", "recurring", 0.85),
  e("linkedin premium", "software", "expense", "recurring", 0.85),
  e("google workspace", "software", "expense", "recurring", 0.85),
  e("google ads", "software", "expense", "recurring", 0.85),
  e("cults3d", "software", "expense", "recurring", 0.85),
  e("flashforge", "software", "expense", "recurring", 0.85),
  e("sp tesbros", "software", "expense", "recurring", 0.85),
  e("tesbros", "software", "expense", "recurring", 0.85),
  e("pinterest", "software", "expense", "recurring", 0.85),
  e("twitter online ads", "software", "expense", "recurring", 0.85),
  e("twitter*", "software", "expense", "recurring", 0.85),
  e("boot.dev", "software", "expense", "recurring", 0.85),
  e("founderscard", "software", "expense", "recurring", 0.85),
];

// ─── Housing — short-term rentals & home improvement merchants ─────────────────
const HOUSING_ENTRIES: RuleSeedEntry[] = [
  // Short-term rentals (one-time)
  e("airbnb", "housing", "expense", "one-time", 0.8),
  e("vrbo", "housing", "expense", "one-time", 0.8),
  e("homeaway", "housing", "expense", "one-time", 0.8),
  // Home improvement (one-time)
  e("home depot", "housing", "expense", "one-time", 0.8),
  e("lowe's", "housing", "expense", "one-time", 0.8),
  e("lowes", "housing", "expense", "one-time", 0.8),
  e("ace hardware", "housing", "expense", "one-time", 0.8),
  e("true value", "housing", "expense", "one-time", 0.8),
  // Mortgage servicers (recurring)
  e("lakeview loan", "housing", "expense", "recurring", 0.8),
  e("lakeview ln", "housing", "expense", "recurring", 0.8),
  e("mr. cooper", "housing", "expense", "recurring", 0.8),
  e("mrcooper", "housing", "expense", "recurring", 0.8),
  e("pennymac", "housing", "expense", "recurring", 0.8),
  e("loancare", "housing", "expense", "recurring", 0.8),
  e("freedom mortgage", "housing", "expense", "recurring", 0.8),
  e("newrez", "housing", "expense", "recurring", 0.8),
  e("phh mortgage", "housing", "expense", "recurring", 0.8),
  e("shellpoint", "housing", "expense", "recurring", 0.8),
  e("flagstar", "housing", "expense", "recurring", 0.8),
  e("nationstar", "housing", "expense", "recurring", 0.8),
  e("ocwen", "housing", "expense", "recurring", 0.8),
  e("caliber home", "housing", "expense", "recurring", 0.8),
  e("homepoint", "housing", "expense", "recurring", 0.8),
  e("roundpoint", "housing", "expense", "recurring", 0.8),
  e("servicemac", "housing", "expense", "recurring", 0.8),
];

// ─── Utilities — named providers ──────────────────────────────────────────────
const UTILITIES_ENTRIES: RuleSeedEntry[] = [
  // Electric utilities
  e("pge", "utilities", "expense", "recurring", 0.85),
  e("pg&e", "utilities", "expense", "recurring", 0.85),
  e("con ed", "utilities", "expense", "recurring", 0.85),
  e("coned", "utilities", "expense", "recurring", 0.85),
  e("duke energy", "utilities", "expense", "recurring", 0.85),
  e("dominion energy", "utilities", "expense", "recurring", 0.85),
  e("southern company", "utilities", "expense", "recurring", 0.85),
  e("eversource", "utilities", "expense", "recurring", 0.85),
  e("national grid", "utilities", "expense", "recurring", 0.85),
  e("dte energy", "utilities", "expense", "recurring", 0.85),
  e("consumers energy", "utilities", "expense", "recurring", 0.85),
  e("we energies", "utilities", "expense", "recurring", 0.85),
  e("xcel energy", "utilities", "expense", "recurring", 0.85),
  e("entergy", "utilities", "expense", "recurring", 0.85),
  e("ameren", "utilities", "expense", "recurring", 0.85),
  e("peco", "utilities", "expense", "recurring", 0.85),
  e("pseg", "utilities", "expense", "recurring", 0.85),
  e("sdge", "utilities", "expense", "recurring", 0.85),
  e("san diego gas", "utilities", "expense", "recurring", 0.85),
  // Internet / phone
  e("comcast", "utilities", "expense", "recurring", 0.85),
  e("xfinity", "utilities", "expense", "recurring", 0.85),
  e("spectrum", "utilities", "expense", "recurring", 0.85),
  e("cox", "utilities", "expense", "recurring", 0.85),
  e("cox cable", "utilities", "expense", "recurring", 0.85),
  e("at&t", "utilities", "expense", "recurring", 0.85),
  e("att.com", "utilities", "expense", "recurring", 0.85),
  e("at t", "utilities", "expense", "recurring", 0.85),
  e("att mobility", "utilities", "expense", "recurring", 0.85),
  e("att wireless", "utilities", "expense", "recurring", 0.85),
  e("verizon", "utilities", "expense", "recurring", 0.85),
  e("t-mobile", "utilities", "expense", "recurring", 0.85),
  e("tmobile", "utilities", "expense", "recurring", 0.85),
  e("sprint", "utilities", "expense", "recurring", 0.85),
  e("boost mobile", "utilities", "expense", "recurring", 0.85),
  e("cricket wireless", "utilities", "expense", "recurring", 0.85),
  e("metro by t-mobile", "utilities", "expense", "recurring", 0.85),
  e("mint mobile", "utilities", "expense", "recurring", 0.85),
  e("visible wireless", "utilities", "expense", "recurring", 0.85),
  e("google fi", "utilities", "expense", "recurring", 0.85),
  // Satellite TV
  e("dish network", "utilities", "expense", "recurring", 0.85),
  e("directv", "utilities", "expense", "recurring", 0.85),
  // Trash / waste
  e("waste management", "utilities", "expense", "recurring", 0.85),
  e("republic services", "utilities", "expense", "recurring", 0.85),
  // Water utilities
  e("california american water", "utilities", "expense", "recurring", 0.85),
  e("american water", "utilities", "expense", "recurring", 0.85),
  e("san jose water", "utilities", "expense", "recurring", 0.85),
  e("california water", "utilities", "expense", "recurring", 0.85),
  e("golden state water", "utilities", "expense", "recurring", 0.85),
  e("bay area water", "utilities", "expense", "recurring", 0.85),
  e("east bay mud", "utilities", "expense", "recurring", 0.85),
  e("mwd", "utilities", "expense", "recurring", 0.85),
  e("sdcwa", "utilities", "expense", "recurring", 0.85),
  e("water authority", "utilities", "expense", "recurring", 0.85),
  e("irrigation district", "utilities", "expense", "recurring", 0.85),
  e("public works", "utilities", "expense", "recurring", 0.85),
  e("city of san diego", "utilities", "expense", "recurring", 0.85),
  e("city water", "utilities", "expense", "recurring", 0.85),
  e("municipal water", "utilities", "expense", "recurring", 0.85),
  // Propane / solar
  e("amerigas", "utilities", "expense", "recurring", 0.85),
  e("ferrellgas", "utilities", "expense", "recurring", 0.85),
  e("suburban propane", "utilities", "expense", "recurring", 0.85),
  e("mosaic solar", "utilities", "expense", "recurring", 0.85),
  e("sunrun", "utilities", "expense", "recurring", 0.85),
  e("solarenergy", "utilities", "expense", "recurring", 0.85),
  e("vivint solar", "utilities", "expense", "recurring", 0.85),
  e("tesla energy", "utilities", "expense", "recurring", 0.85),
  // HVAC
  e("goettl", "utilities", "expense", "recurring", 0.85),
];

// ─── Travel — airlines, hotels, booking platforms, rental cars ────────────────
const TRAVEL_ENTRIES: RuleSeedEntry[] = [
  e("united airlines", "travel", "expense", "one-time", 0.85),
  e("delta airlines", "travel", "expense", "one-time", 0.85),
  e("american airlines", "travel", "expense", "one-time", 0.85),
  e("southwest airlines", "travel", "expense", "one-time", 0.85),
  e("jetblue", "travel", "expense", "one-time", 0.85),
  e("alaska airlines", "travel", "expense", "one-time", 0.85),
  e("spirit airlines", "travel", "expense", "one-time", 0.85),
  e("frontier airlines", "travel", "expense", "one-time", 0.85),
  e("lufthansa", "travel", "expense", "one-time", 0.85),
  e("british airways", "travel", "expense", "one-time", 0.85),
  e("air france", "travel", "expense", "one-time", 0.85),
  e("emirates", "travel", "expense", "one-time", 0.85),
  e("ryanair", "travel", "expense", "one-time", 0.85),
  e("easyjet", "travel", "expense", "one-time", 0.85),
  e("air canada", "travel", "expense", "one-time", 0.85),
  e("westjet", "travel", "expense", "one-time", 0.85),
  e("marriott", "travel", "expense", "one-time", 0.85),
  e("hilton", "travel", "expense", "one-time", 0.85),
  e("hyatt", "travel", "expense", "one-time", 0.85),
  e("ihg", "travel", "expense", "one-time", 0.85),
  e("sheraton", "travel", "expense", "one-time", 0.85),
  e("westin", "travel", "expense", "one-time", 0.85),
  e("holiday inn", "travel", "expense", "one-time", 0.85),
  e("best western", "travel", "expense", "one-time", 0.85),
  e("radisson", "travel", "expense", "one-time", 0.85),
  e("wyndham", "travel", "expense", "one-time", 0.85),
  e("fairfield", "travel", "expense", "one-time", 0.85),
  e("hampton inn", "travel", "expense", "one-time", 0.85),
  e("doubletree", "travel", "expense", "one-time", 0.85),
  e("motel 6", "travel", "expense", "one-time", 0.85),
  e("extended stay", "travel", "expense", "one-time", 0.85),
  e("travelodge", "travel", "expense", "one-time", 0.85),
  e("days inn", "travel", "expense", "one-time", 0.85),
  e("super 8", "travel", "expense", "one-time", 0.85),
  e("comfort inn", "travel", "expense", "one-time", 0.85),
  e("quality inn", "travel", "expense", "one-time", 0.85),
  e("la quinta", "travel", "expense", "one-time", 0.85),
  e("expedia", "travel", "expense", "one-time", 0.85),
  e("booking.com", "travel", "expense", "one-time", 0.85),
  e("hotels.com", "travel", "expense", "one-time", 0.85),
  e("priceline", "travel", "expense", "one-time", 0.85),
  e("kayak", "travel", "expense", "one-time", 0.85),
  e("travelocity", "travel", "expense", "one-time", 0.85),
  e("hotwire", "travel", "expense", "one-time", 0.85),
  e("trivago", "travel", "expense", "one-time", 0.85),
  e("orbitz", "travel", "expense", "one-time", 0.85),
  e("amtrak", "travel", "expense", "one-time", 0.85),
  e("greyhound", "travel", "expense", "one-time", 0.85),
  e("megabus", "travel", "expense", "one-time", 0.85),
  e("flixbus", "travel", "expense", "one-time", 0.85),
  e("enterprise rent", "travel", "expense", "one-time", 0.85),
  e("hertz", "travel", "expense", "one-time", 0.85),
  e("avis", "travel", "expense", "one-time", 0.85),
  e("budget car", "travel", "expense", "one-time", 0.85),
  e("national car", "travel", "expense", "one-time", 0.85),
  e("alamo", "travel", "expense", "one-time", 0.85),
  e("thrifty car", "travel", "expense", "one-time", 0.85),
  e("dollar rental", "travel", "expense", "one-time", 0.85),
  e("zipcar", "travel", "expense", "one-time", 0.85),
  e("turo", "travel", "expense", "one-time", 0.85),
];

// ─── Gas — named stations ─────────────────────────────────────────────────────
const GAS_ENTRIES: RuleSeedEntry[] = [
  e("shell", "gas", "expense", "one-time", 0.85),
  e("exxon", "gas", "expense", "one-time", 0.85),
  e("chevron", "gas", "expense", "one-time", 0.85),
  e("bp", "gas", "expense", "one-time", 0.85),
  e("mobil", "gas", "expense", "one-time", 0.85),
  e("mobil gas", "gas", "expense", "one-time", 0.85),
  e("exxonmobil", "gas", "expense", "one-time", 0.85),
  e("citgo", "gas", "expense", "one-time", 0.85),
  e("sunoco", "gas", "expense", "one-time", 0.85),
  e("speedway", "gas", "expense", "one-time", 0.85),
  e("marathon gas", "gas", "expense", "one-time", 0.85),
  e("racetrac", "gas", "expense", "one-time", 0.85),
  e("pilot flying j", "gas", "expense", "one-time", 0.85),
  e("loves travel", "gas", "expense", "one-time", 0.85),
  e("flying j", "gas", "expense", "one-time", 0.85),
];

// ─── Parking — named apps ─────────────────────────────────────────────────────
const PARKING_ENTRIES: RuleSeedEntry[] = [
  e("parkwhiz", "parking", "expense", "one-time", 0.85),
  e("spothero", "parking", "expense", "one-time", 0.85),
  e("parkmobile", "parking", "expense", "one-time", 0.85),
  e("bestparking", "parking", "expense", "one-time", 0.85),
  e("laparking", "parking", "expense", "one-time", 0.85),
  e("impark", "parking", "expense", "one-time", 0.85),
  e("indigo park", "parking", "expense", "one-time", 0.85),
];

// ─── Auto — named repair/parts shops ─────────────────────────────────────────
const AUTO_ENTRIES: RuleSeedEntry[] = [
  e("autozone", "auto", "expense", "one-time", 0.8),
  e("o'reilly auto", "auto", "expense", "one-time", 0.8),
  e("advance auto", "auto", "expense", "one-time", 0.8),
  e("napa auto", "auto", "expense", "one-time", 0.8),
  e("pep boys", "auto", "expense", "one-time", 0.8),
  e("jiffy lube", "auto", "expense", "one-time", 0.8),
  e("jiffy", "auto", "expense", "one-time", 0.8),
  e("valvoline", "auto", "expense", "one-time", 0.8),
  e("firestone", "auto", "expense", "one-time", 0.8),
  e("goodyear tire", "auto", "expense", "one-time", 0.8),
  e("discount tire", "auto", "expense", "one-time", 0.8),
  e("americas tire", "auto", "expense", "one-time", 0.8),
  e("mavis discount", "auto", "expense", "one-time", 0.8),
  e("midas", "auto", "expense", "one-time", 0.8),
  e("meineke", "auto", "expense", "one-time", 0.8),
  e("big o tire", "auto", "expense", "one-time", 0.8),
  e("ntb tire", "auto", "expense", "one-time", 0.8),
  e("christian brothers auto", "auto", "expense", "one-time", 0.8),
  e("aamco", "auto", "expense", "one-time", 0.8),
  e("luv car wa", "auto", "expense", "one-time", 0.8),
  e("hansshow", "auto", "expense", "one-time", 0.8),
];

// ─── Groceries — named chains ──────────────────────────────────────────────────
const GROCERY_ENTRIES: RuleSeedEntry[] = [
  e("whole foods", "groceries", "expense", "one-time", 0.85),
  e("wholefoods", "groceries", "expense", "one-time", 0.85),
  e("wholefoodsmarket", "groceries", "expense", "one-time", 0.85),
  e("trader joe", "groceries", "expense", "one-time", 0.85),
  e("trader joes", "groceries", "expense", "one-time", 0.85),
  e("traderjoes", "groceries", "expense", "one-time", 0.85),
  e("kroger", "groceries", "expense", "one-time", 0.85),
  e("ralphs", "groceries", "expense", "one-time", 0.85),
  e("fry's food", "groceries", "expense", "one-time", 0.85),
  e("smith's food", "groceries", "expense", "one-time", 0.85),
  e("king soopers", "groceries", "expense", "one-time", 0.85),
  e("fred meyer", "groceries", "expense", "one-time", 0.85),
  e("qfc", "groceries", "expense", "one-time", 0.85),
  e("harris teeter", "groceries", "expense", "one-time", 0.85),
  e("safeway", "groceries", "expense", "one-time", 0.85),
  e("publix", "groceries", "expense", "one-time", 0.85),
  e("aldi", "groceries", "expense", "one-time", 0.85),
  e("lidl", "groceries", "expense", "one-time", 0.85),
  e("costco", "groceries", "expense", "one-time", 0.85),
  e("sam's club", "groceries", "expense", "one-time", 0.85),
  e("sams club", "groceries", "expense", "one-time", 0.85),
  e("bj's wholesale", "groceries", "expense", "one-time", 0.85),
  e("bjs wholesale", "groceries", "expense", "one-time", 0.85),
  e("walmart supercenter", "groceries", "expense", "one-time", 0.85),
  e("walmart grocery", "groceries", "expense", "one-time", 0.85),
  e("walmart neighborhood", "groceries", "expense", "one-time", 0.85),
  e("market basket", "groceries", "expense", "one-time", 0.85),
  e("food lion", "groceries", "expense", "one-time", 0.85),
  e("wegmans", "groceries", "expense", "one-time", 0.85),
  e("sprouts", "groceries", "expense", "one-time", 0.85),
  e("fresh market", "groceries", "expense", "one-time", 0.85),
  e("fresh thyme", "groceries", "expense", "one-time", 0.85),
  e("natural grocers", "groceries", "expense", "one-time", 0.85),
  e("h-e-b", "groceries", "expense", "one-time", 0.85),
  e("heb", "groceries", "expense", "one-time", 0.85),
  e("meijer", "groceries", "expense", "one-time", 0.85),
  e("giant food", "groceries", "expense", "one-time", 0.85),
  e("stop & shop", "groceries", "expense", "one-time", 0.85),
  e("stop and shop", "groceries", "expense", "one-time", 0.85),
  e("shop rite", "groceries", "expense", "one-time", 0.85),
  e("shoprite", "groceries", "expense", "one-time", 0.85),
  e("acme markets", "groceries", "expense", "one-time", 0.85),
  e("winn-dixie", "groceries", "expense", "one-time", 0.85),
  e("winndixie", "groceries", "expense", "one-time", 0.85),
  e("food 4 less", "groceries", "expense", "one-time", 0.85),
  e("food max", "groceries", "expense", "one-time", 0.85),
  e("smart & final", "groceries", "expense", "one-time", 0.85),
  e("stater bros", "groceries", "expense", "one-time", 0.85),
  e("price chopper", "groceries", "expense", "one-time", 0.85),
  e("hannaford", "groceries", "expense", "one-time", 0.85),
  e("iga supermarket", "groceries", "expense", "one-time", 0.85),
  e("piggly wiggly", "groceries", "expense", "one-time", 0.85),
  e("hy-vee", "groceries", "expense", "one-time", 0.85),
  e("jewel-osco", "groceries", "expense", "one-time", 0.85),
  e("dominick's", "groceries", "expense", "one-time", 0.85),
  e("randalls", "groceries", "expense", "one-time", 0.85),
  e("tom thumb", "groceries", "expense", "one-time", 0.85),
  e("vons", "groceries", "expense", "one-time", 0.85),
  e("pavilions", "groceries", "expense", "one-time", 0.85),
  e("albertsons", "groceries", "expense", "one-time", 0.85),
  e("lucky supermarket", "groceries", "expense", "one-time", 0.85),
  e("save mart", "groceries", "expense", "one-time", 0.85),
  e("raley's", "groceries", "expense", "one-time", 0.85),
  e("winco foods", "groceries", "expense", "one-time", 0.85),
  e("dillons", "groceries", "expense", "one-time", 0.85),
  e("99 ranch", "groceries", "expense", "one-time", 0.85),
  e("h mart", "groceries", "expense", "one-time", 0.85),
  e("hmart", "groceries", "expense", "one-time", 0.85),
  e("mitsuwa", "groceries", "expense", "one-time", 0.85),
  e("nijiya", "groceries", "expense", "one-time", 0.85),
  e("zion market", "groceries", "expense", "one-time", 0.85),
  e("marukai", "groceries", "expense", "one-time", 0.85),
  e("hong kong market", "groceries", "expense", "one-time", 0.85),
  e("ranch 99", "groceries", "expense", "one-time", 0.85),
  e("el super", "groceries", "expense", "one-time", 0.85),
  e("northgate market", "groceries", "expense", "one-time", 0.85),
  e("cardenas", "groceries", "expense", "one-time", 0.85),
  e("vallarta supermarket", "groceries", "expense", "one-time", 0.85),
];

// ─── Coffee — named chains ─────────────────────────────────────────────────────
const COFFEE_ENTRIES: RuleSeedEntry[] = [
  e("starbucks", "coffee", "expense", "one-time", 0.85),
  e("sbux", "coffee", "expense", "one-time", 0.85),
  e("dunkin", "coffee", "expense", "one-time", 0.85),
  e("dunkin donuts", "coffee", "expense", "one-time", 0.85),
  e("dunkin'", "coffee", "expense", "one-time", 0.85),
  e("dutch bros", "coffee", "expense", "one-time", 0.85),
  e("peet's coffee", "coffee", "expense", "one-time", 0.85),
  e("peets coffee", "coffee", "expense", "one-time", 0.85),
  e("caribou coffee", "coffee", "expense", "one-time", 0.85),
  e("tim hortons", "coffee", "expense", "one-time", 0.85),
  e("coffee bean", "coffee", "expense", "one-time", 0.85),
  e("biggby", "coffee", "expense", "one-time", 0.85),
  e("scooter's coffee", "coffee", "expense", "one-time", 0.85),
  e("human bean", "coffee", "expense", "one-time", 0.85),
  e("black rock coffee", "coffee", "expense", "one-time", 0.85),
  e("portafilter", "coffee", "expense", "one-time", 0.85),
];

// ─── Delivery — apps and meal kits ────────────────────────────────────────────
const DELIVERY_ENTRIES: RuleSeedEntry[] = [
  e("doordash", "delivery", "expense", "one-time", 0.9),
  e("ubereats", "delivery", "expense", "one-time", 0.9),
  e("uber eats", "delivery", "expense", "one-time", 0.9),
  e("grubhub", "delivery", "expense", "one-time", 0.9),
  e("postmates", "delivery", "expense", "one-time", 0.9),
  e("seamless", "delivery", "expense", "one-time", 0.9),
  e("caviar food", "delivery", "expense", "one-time", 0.9),
  e("drizly", "delivery", "expense", "one-time", 0.9),
  e("gopuff", "delivery", "expense", "one-time", 0.9),
  e("instacart", "delivery", "expense", "one-time", 0.9),
  e("shipt", "delivery", "expense", "one-time", 0.9),
  // Meal kit services (recurring)
  e("factor 75", "delivery", "expense", "recurring", 0.9),
  e("factor75", "delivery", "expense", "recurring", 0.9),
  e("hello fresh", "delivery", "expense", "recurring", 0.9),
  e("hellofresh", "delivery", "expense", "recurring", 0.9),
  e("home chef", "delivery", "expense", "recurring", 0.9),
  e("green chef", "delivery", "expense", "recurring", 0.9),
  e("everyplate", "delivery", "expense", "recurring", 0.9),
  e("marley spoon", "delivery", "expense", "recurring", 0.9),
  e("gobble", "delivery", "expense", "recurring", 0.9),
  e("freshly", "delivery", "expense", "recurring", 0.9),
];

// ─── Convenience — named stores ───────────────────────────────────────────────
const CONVENIENCE_ENTRIES: RuleSeedEntry[] = [
  e("7-eleven", "convenience", "expense", "one-time", 0.85),
  e("7 eleven", "convenience", "expense", "one-time", 0.85),
  e("7-11", "convenience", "expense", "one-time", 0.85),
  e("circle k", "convenience", "expense", "one-time", 0.85),
  e("wawa", "convenience", "expense", "one-time", 0.85),
  e("kwik trip", "convenience", "expense", "one-time", 0.85),
  e("kwik star", "convenience", "expense", "one-time", 0.85),
  e("casey's general", "convenience", "expense", "one-time", 0.85),
  e("casey's", "convenience", "expense", "one-time", 0.85),
  e("sheetz", "convenience", "expense", "one-time", 0.85),
  e("holiday station", "convenience", "expense", "one-time", 0.85),
  e("cumberland farms", "convenience", "expense", "one-time", 0.85),
  e("thorntons", "convenience", "expense", "one-time", 0.85),
  e("united dairy farmers", "convenience", "expense", "one-time", 0.85),
  e("bp convenience", "convenience", "expense", "one-time", 0.85),
  e("exxon convenience", "convenience", "expense", "one-time", 0.85),
];

// ─── Dining — named chains ─────────────────────────────────────────────────────
const DINING_ENTRIES: RuleSeedEntry[] = [
  e("chipotle", "dining", "expense", "one-time", 0.8),
  e("mcdonald", "dining", "expense", "one-time", 0.8),
  e("mcdonalds", "dining", "expense", "one-time", 0.8),
  e("mcd", "dining", "expense", "one-time", 0.8),
  e("subway sandwich", "dining", "expense", "one-time", 0.8),
  e("domino", "dining", "expense", "one-time", 0.8),
  e("pizza hut", "dining", "expense", "one-time", 0.8),
  e("papa john", "dining", "expense", "one-time", 0.8),
  e("little caesar", "dining", "expense", "one-time", 0.8),
  e("burger king", "dining", "expense", "one-time", 0.8),
  e("chick-fil-a", "dining", "expense", "one-time", 0.8),
  e("chickfila", "dining", "expense", "one-time", 0.8),
  e("panera", "dining", "expense", "one-time", 0.8),
  e("chili's", "dining", "expense", "one-time", 0.8),
  e("olive garden", "dining", "expense", "one-time", 0.8),
  e("outback steakhouse", "dining", "expense", "one-time", 0.8),
  e("applebees", "dining", "expense", "one-time", 0.8),
  e("tgi friday", "dining", "expense", "one-time", 0.8),
  e("ihop", "dining", "expense", "one-time", 0.8),
  e("waffle house", "dining", "expense", "one-time", 0.8),
  e("denny's", "dining", "expense", "one-time", 0.8),
  e("red lobster", "dining", "expense", "one-time", 0.8),
  e("longhorn steakhouse", "dining", "expense", "one-time", 0.8),
  e("texas roadhouse", "dining", "expense", "one-time", 0.8),
  e("five guys", "dining", "expense", "one-time", 0.8),
  e("shake shack", "dining", "expense", "one-time", 0.8),
  e("in-n-out", "dining", "expense", "one-time", 0.8),
  e("in n out", "dining", "expense", "one-time", 0.8),
  e("whataburger", "dining", "expense", "one-time", 0.8),
  e("sonic drive", "dining", "expense", "one-time", 0.8),
  e("jack in the box", "dining", "expense", "one-time", 0.8),
  e("del taco", "dining", "expense", "one-time", 0.8),
  e("qdoba", "dining", "expense", "one-time", 0.8),
  e("popeyes", "dining", "expense", "one-time", 0.8),
  e("church's chicken", "dining", "expense", "one-time", 0.8),
  e("kfc", "dining", "expense", "one-time", 0.8),
  e("kentucky fried", "dining", "expense", "one-time", 0.8),
  e("raising cane", "dining", "expense", "one-time", 0.8),
  e("zaxby", "dining", "expense", "one-time", 0.8),
  e("wingstop", "dining", "expense", "one-time", 0.8),
  e("buffalo wild", "dining", "expense", "one-time", 0.8),
  e("jersey mike", "dining", "expense", "one-time", 0.8),
  e("jimmy john", "dining", "expense", "one-time", 0.8),
  e("firehouse sub", "dining", "expense", "one-time", 0.8),
  e("potbelly", "dining", "expense", "one-time", 0.8),
  e("jason's deli", "dining", "expense", "one-time", 0.8),
  e("which wich", "dining", "expense", "one-time", 0.8),
  e("moe's southwest", "dining", "expense", "one-time", 0.8),
  e("habit burger", "dining", "expense", "one-time", 0.8),
];

// ─── Medical — pharmacies, labs, vision, telehealth ───────────────────────────
const MEDICAL_ENTRIES: RuleSeedEntry[] = [
  e("cvs", "medical", "expense", "one-time", 0.8),
  e("walgreens", "medical", "expense", "one-time", 0.8),
  e("rite aid", "medical", "expense", "one-time", 0.8),
  e("riteaid", "medical", "expense", "one-time", 0.8),
  e("duane reade", "medical", "expense", "one-time", 0.8),
  e("health mart", "medical", "expense", "one-time", 0.8),
  e("medicine shoppe", "medical", "expense", "one-time", 0.8),
  e("lenscrafters", "medical", "expense", "one-time", 0.8),
  e("america's best", "medical", "expense", "one-time", 0.8),
  e("visionworks", "medical", "expense", "one-time", 0.8),
  e("labcorp", "medical", "expense", "one-time", 0.8),
  e("lab corp", "medical", "expense", "one-time", 0.8),
  e("quest diagnostics", "medical", "expense", "one-time", 0.8),
  e("questdiagnostics", "medical", "expense", "one-time", 0.8),
  e("planned parenthood", "medical", "expense", "one-time", 0.8),
  e("talkspace", "medical", "expense", "recurring", 0.8),
  e("betterhelp", "medical", "expense", "recurring", 0.8),
  e("cerebral health", "medical", "expense", "recurring", 0.8),
  e("gnc", "medical", "expense", "one-time", 0.8),
  e("vitamin shoppe", "medical", "expense", "one-time", 0.8),
  e("23andme", "medical", "expense", "one-time", 0.8),
  e("drogueria", "medical", "expense", "one-time", 0.8),
  e("farmacia", "medical", "expense", "one-time", 0.8),
];

// ─── Fitness — named gyms and studios ─────────────────────────────────────────
const FITNESS_ENTRIES: RuleSeedEntry[] = [
  e("planet fitness", "fitness", "expense", "recurring", 0.82),
  e("la fitness", "fitness", "expense", "recurring", 0.82),
  e("24 hour fitness", "fitness", "expense", "recurring", 0.82),
  e("lifetime fitness", "fitness", "expense", "recurring", 0.82),
  e("anytime fitness", "fitness", "expense", "recurring", 0.82),
  e("equinox", "fitness", "expense", "recurring", 0.82),
  e("crunch fitness", "fitness", "expense", "recurring", 0.82),
  e("blink fitness", "fitness", "expense", "recurring", 0.82),
  e("blink gym", "fitness", "expense", "recurring", 0.82),
  e("blink", "fitness", "expense", "recurring", 0.82),
  e("ymca", "fitness", "expense", "recurring", 0.82),
  e("crossfit", "fitness", "expense", "recurring", 0.82),
  e("orangetheory", "fitness", "expense", "recurring", 0.82),
  e("pure barre", "fitness", "expense", "recurring", 0.82),
  e("soulcycle", "fitness", "expense", "recurring", 0.82),
  e("peloton", "fitness", "expense", "recurring", 0.82),
  e("noom", "fitness", "expense", "recurring", 0.82),
  e("weight watcher", "fitness", "expense", "recurring", 0.82),
  e("nutrisystem", "fitness", "expense", "recurring", 0.82),
];

// ─── Software — online education platforms ────────────────────────────────────
const EDUCATION_SOFTWARE_ENTRIES: RuleSeedEntry[] = [
  e("coursera", "software", "expense", "recurring", 0.82),
  e("udemy", "software", "expense", "recurring", 0.82),
  e("skillshare", "software", "expense", "recurring", 0.82),
  e("linkedin learning", "software", "expense", "recurring", 0.82),
  e("pluralsight", "software", "expense", "recurring", 0.82),
  e("datacamp", "software", "expense", "recurring", 0.82),
  e("codecademy", "software", "expense", "recurring", 0.82),
  e("treehouse", "software", "expense", "recurring", 0.82),
  e("udacity", "software", "expense", "recurring", 0.82),
  e("khan academy", "software", "expense", "recurring", 0.82),
  e("chegg", "software", "expense", "recurring", 0.82),
  e("course hero", "software", "expense", "recurring", 0.82),
  e("quizlet", "software", "expense", "recurring", 0.82),
  e("brilliant.org", "software", "expense", "recurring", 0.82),
  e("duolingo", "software", "expense", "recurring", 0.82),
];

// ─── Shopping — specific childcare centers ────────────────────────────────────
const CHILDCARE_ENTRIES: RuleSeedEntry[] = [
  e("bright horizons", "shopping", "expense", "recurring", 0.78),
  e("kindercare", "shopping", "expense", "recurring", 0.78),
  e("learning care", "shopping", "expense", "recurring", 0.78),
];

// ─── Shopping — specific charity organizations ────────────────────────────────
const CHARITY_ENTRIES: RuleSeedEntry[] = [
  e("gofundme", "shopping", "expense", "one-time", 0.68),
  e("united way", "shopping", "expense", "one-time", 0.68),
  e("red cross", "shopping", "expense", "one-time", 0.68),
  e("salvation army", "shopping", "expense", "one-time", 0.68),
  e("goodwill", "shopping", "expense", "one-time", 0.68),
  e("habitat for humanity", "shopping", "expense", "one-time", 0.68),
  e("oxfam", "shopping", "expense", "one-time", 0.68),
  e("doctors without borders", "shopping", "expense", "one-time", 0.68),
  e("msf usa", "shopping", "expense", "one-time", 0.68),
  e("unicef", "shopping", "expense", "one-time", 0.68),
  e("aclu", "shopping", "expense", "one-time", 0.68),
];

// ─── Entertainment — venue chains, gaming platforms ───────────────────────────
const ENTERTAINMENT_VENUE_ENTRIES: RuleSeedEntry[] = [
  e("amc", "entertainment", "expense", "one-time", 0.75),
  e("regal cinema", "entertainment", "expense", "one-time", 0.75),
  e("cinemark", "entertainment", "expense", "one-time", 0.75),
  e("ticketmaster", "entertainment", "expense", "one-time", 0.75),
  e("stubhub", "entertainment", "expense", "one-time", 0.75),
  e("seatgeek", "entertainment", "expense", "one-time", 0.75),
  e("vivid seats", "entertainment", "expense", "one-time", 0.75),
  e("eventbrite", "entertainment", "expense", "one-time", 0.75),
  e("six flags", "entertainment", "expense", "one-time", 0.75),
  e("cedar point", "entertainment", "expense", "one-time", 0.75),
  e("universal studios", "entertainment", "expense", "one-time", 0.75),
  e("disney world", "entertainment", "expense", "one-time", 0.75),
  e("disneyland", "entertainment", "expense", "one-time", 0.75),
  e("seaworld", "entertainment", "expense", "one-time", 0.75),
  e("steam game", "entertainment", "expense", "one-time", 0.75),
  e("steam purchase", "entertainment", "expense", "one-time", 0.75),
  e("playstation store", "entertainment", "expense", "one-time", 0.75),
  e("psn", "entertainment", "expense", "one-time", 0.75),
  e("xbox store", "entertainment", "expense", "one-time", 0.75),
  e("nintendo eshop", "entertainment", "expense", "one-time", 0.75),
  e("epic games", "entertainment", "expense", "one-time", 0.75),
  e("riot games", "entertainment", "expense", "one-time", 0.75),
  e("blizzard", "entertainment", "expense", "one-time", 0.75),
  e("activision", "entertainment", "expense", "one-time", 0.75),
  e("ea sports", "entertainment", "expense", "one-time", 0.75),
  e("ubisoft", "entertainment", "expense", "one-time", 0.75),
  e("2k games", "entertainment", "expense", "one-time", 0.75),
  e("humble bundle", "entertainment", "expense", "one-time", 0.75),
];

// ─── Shopping — broad retail chains ───────────────────────────────────────────
const SHOPPING_ENTRIES: RuleSeedEntry[] = [
  e("amazon", "shopping", "expense", "one-time", 0.7),
  e("amzn", "shopping", "expense", "one-time", 0.7),
  e("walmart", "shopping", "expense", "one-time", 0.7),
  e("best buy", "shopping", "expense", "one-time", 0.7),
  e("ikea", "shopping", "expense", "one-time", 0.7),
  e("etsy", "shopping", "expense", "one-time", 0.7),
  e("ebay", "shopping", "expense", "one-time", 0.7),
  e("nike", "shopping", "expense", "one-time", 0.7),
  e("adidas", "shopping", "expense", "one-time", 0.7),
  e("nordstrom", "shopping", "expense", "one-time", 0.7),
  e("macy", "shopping", "expense", "one-time", 0.7),
  e("tj maxx", "shopping", "expense", "one-time", 0.7),
  e("tjmaxx", "shopping", "expense", "one-time", 0.7),
  e("marshalls", "shopping", "expense", "one-time", 0.7),
  e("ross stores", "shopping", "expense", "one-time", 0.7),
  e("old navy", "shopping", "expense", "one-time", 0.7),
  e("gap", "shopping", "expense", "one-time", 0.7),
  e("banana republic", "shopping", "expense", "one-time", 0.7),
  e("zara", "shopping", "expense", "one-time", 0.7),
  e("h&m", "shopping", "expense", "one-time", 0.7),
  e("uniqlo", "shopping", "expense", "one-time", 0.7),
  e("forever 21", "shopping", "expense", "one-time", 0.7),
  e("express clothing", "shopping", "expense", "one-time", 0.7),
  e("victoria's secret", "shopping", "expense", "one-time", 0.7),
  e("bath & body", "shopping", "expense", "one-time", 0.7),
  e("bed bath", "shopping", "expense", "one-time", 0.7),
  e("williams sonoma", "shopping", "expense", "one-time", 0.7),
  e("pottery barn", "shopping", "expense", "one-time", 0.7),
  e("west elm", "shopping", "expense", "one-time", 0.7),
  e("restoration hardware", "shopping", "expense", "one-time", 0.7),
  e("pier 1", "shopping", "expense", "one-time", 0.7),
  e("tuesday morning", "shopping", "expense", "one-time", 0.7),
  e("five below", "shopping", "expense", "one-time", 0.7),
  e("dollar tree", "shopping", "expense", "one-time", 0.7),
  e("dollartree", "shopping", "expense", "one-time", 0.7),
  e("dollar general", "shopping", "expense", "one-time", 0.7),
  e("dollargeneral", "shopping", "expense", "one-time", 0.7),
  e("family dollar", "shopping", "expense", "one-time", 0.7),
  e("familydollar", "shopping", "expense", "one-time", 0.7),
  e("big lots", "shopping", "expense", "one-time", 0.7),
  e("kohls", "shopping", "expense", "one-time", 0.7),
  e("jcpenney", "shopping", "expense", "one-time", 0.7),
  e("sears", "shopping", "expense", "one-time", 0.7),
  e("jcp", "shopping", "expense", "one-time", 0.7),
  e("newegg", "shopping", "expense", "one-time", 0.7),
  e("b&h photo", "shopping", "expense", "one-time", 0.7),
  e("bhphotovideo", "shopping", "expense", "one-time", 0.7),
  e("micro center", "shopping", "expense", "one-time", 0.7),
  e("fry's electronics", "shopping", "expense", "one-time", 0.7),
  e("staples", "shopping", "expense", "one-time", 0.7),
  e("office depot", "shopping", "expense", "one-time", 0.7),
  e("officemax", "shopping", "expense", "one-time", 0.7),
  e("container store", "shopping", "expense", "one-time", 0.7),
  e("world market", "shopping", "expense", "one-time", 0.7),
  e("crate & barrel", "shopping", "expense", "one-time", 0.7),
  e("target", "shopping", "expense", "one-time", 0.7),
  e("petco", "shopping", "expense", "one-time", 0.7),
  e("petsmart", "shopping", "expense", "one-time", 0.7),
  e("chewy", "shopping", "expense", "one-time", 0.7),
  e("tractor supply", "shopping", "expense", "one-time", 0.7),
  e("cabela", "shopping", "expense", "one-time", 0.7),
  e("bass pro", "shopping", "expense", "one-time", 0.7),
  e("rei", "shopping", "expense", "one-time", 0.7),
  e("dick's sporting", "shopping", "expense", "one-time", 0.7),
  e("academy sports", "shopping", "expense", "one-time", 0.7),
  e("modell's", "shopping", "expense", "one-time", 0.7),
  e("sport chalet", "shopping", "expense", "one-time", 0.7),
  e("foot locker", "shopping", "expense", "one-time", 0.7),
  e("finish line", "shopping", "expense", "one-time", 0.7),
  e("journeys", "shopping", "expense", "one-time", 0.7),
  e("dsw", "shopping", "expense", "one-time", 0.7),
  e("payless", "shopping", "expense", "one-time", 0.7),
  e("shoe carnival", "shopping", "expense", "one-time", 0.7),
  e("famous footwear", "shopping", "expense", "one-time", 0.7),
  e("skechers", "shopping", "expense", "one-time", 0.7),
  e("ugg", "shopping", "expense", "one-time", 0.7),
  e("lululemon", "shopping", "expense", "one-time", 0.7),
  e("athleta", "shopping", "expense", "one-time", 0.7),
  e("under armour", "shopping", "expense", "one-time", 0.7),
  e("columbia sportswear", "shopping", "expense", "one-time", 0.7),
  e("the north face", "shopping", "expense", "one-time", 0.7),
  e("patagonia", "shopping", "expense", "one-time", 0.7),
  e("michaels store", "shopping", "expense", "one-time", 0.7),
  e("hobby lobby", "shopping", "expense", "one-time", 0.7),
  e("joann fabric", "shopping", "expense", "one-time", 0.7),
  e("overstock", "shopping", "expense", "one-time", 0.7),
  e("wayfair", "shopping", "expense", "one-time", 0.7),
  e("wish.com", "shopping", "expense", "one-time", 0.7),
  e("temu", "shopping", "expense", "one-time", 0.7),
  e("shein", "shopping", "expense", "one-time", 0.7),
  e("aliexpress", "shopping", "expense", "one-time", 0.7),
  e("alibaba", "shopping", "expense", "one-time", 0.7),
  e("romwe", "shopping", "expense", "one-time", 0.7),
  e("zaful", "shopping", "expense", "one-time", 0.7),
  e("fashion nova", "shopping", "expense", "one-time", 0.7),
  e("pretty little thing", "shopping", "expense", "one-time", 0.7),
  e("boohoo", "shopping", "expense", "one-time", 0.7),
  e("revolve", "shopping", "expense", "one-time", 0.7),
  e("asos", "shopping", "expense", "one-time", 0.7),
  e("urban outfitters", "shopping", "expense", "one-time", 0.7),
  e("anthropologie", "shopping", "expense", "one-time", 0.7),
  e("free people", "shopping", "expense", "one-time", 0.7),
  e("depop", "shopping", "expense", "one-time", 0.7),
  e("poshmark", "shopping", "expense", "one-time", 0.7),
  e("mercari", "shopping", "expense", "one-time", 0.7),
  e("thredup", "shopping", "expense", "one-time", 0.7),
  e("costco.com", "shopping", "expense", "one-time", 0.7),
  e("samsclub", "shopping", "expense", "one-time", 0.7),
  e("storenvy", "shopping", "expense", "one-time", 0.7),
];

// ─── Exported array (order: highest confidence first) ─────────────────────────
export const RULE_SEED_ENTRIES: RuleSeedEntry[] = [
  ...DEBT_ENTRIES,
  ...INSURANCE_ENTRIES,
  ...STREAMING_ENTRIES,
  ...SOFTWARE_CONSUMER_ENTRIES,
  ...SOFTWARE_BUSINESS_ENTRIES,
  ...HOUSING_ENTRIES,
  ...UTILITIES_ENTRIES,
  ...TRAVEL_ENTRIES,
  ...GAS_ENTRIES,
  ...PARKING_ENTRIES,
  ...AUTO_ENTRIES,
  ...GROCERY_ENTRIES,
  ...COFFEE_ENTRIES,
  ...DELIVERY_ENTRIES,
  ...CONVENIENCE_ENTRIES,
  ...DINING_ENTRIES,
  ...MEDICAL_ENTRIES,
  ...FITNESS_ENTRIES,
  ...EDUCATION_SOFTWARE_ENTRIES,
  ...CHILDCARE_ENTRIES,
  ...CHARITY_ENTRIES,
  ...ENTERTAINMENT_VENUE_ENTRIES,
  ...SHOPPING_ENTRIES,
];
