/**
 * Rules-based transaction classifier.
 *
 * Assigns category, transaction class, recurrence hints, and a human-readable
 * label reason using keyword matching against the merchant name. Rules are
 * intentionally deterministic and explainable (V1 spec section 10.2).
 *
 * The keyword tables below drive classification. Each entry maps a set of
 * merchant substrings to a category. Order matters: the first matching rule
 * wins, so more specific patterns should appear before broader ones.
 */
import type { V1Category } from "../shared/schema.js";

const TRANSFER_KEYWORDS = [
  "transfer",
  "xfer",
  "zelle",
  "venmo",
  "cash app",
  "cashapp",
  "wire",
  "paypal",
  "apple pay",
  "google pay",
  "samsung pay",
  "peer transfer",
  "p2p",
  "remittance",
  "western union",
  "moneygram",
  "wise transfer",
  "revolut",
];

export type ClassificationResult = {
  transactionClass: "income" | "expense" | "transfer" | "refund";
  category: V1Category;
  recurrenceType: "recurring" | "one-time";
  labelSource: "rule";
  labelConfidence: number;
  labelReason: string;
  flowOverride: "outflow" | null;
};

type CategoryRule = {
  category: V1Category;
  keywords: string[];
  confidence: number;
};

/**
 * Keyword rules ordered from specific to general. Each keyword is matched
 * as a case-insensitive substring of the merchant name.
 */
const CATEGORY_RULES: CategoryRule[] = [
  // Transfers (check before income — "transfer" can appear in inflows too)
  {
    category: "transfers",
    keywords: TRANSFER_KEYWORDS,
    confidence: 0.85,
  },

  // Debt payments
  {
    category: "debt",
    keywords: [
      "loan payment",
      "student loan",
      "auto loan",
      "car payment",
      "credit card payment",
      "sallie mae",
      "navient",
      "great lakes",
      "fedloan",
      "mohela",
      "nelnet",
      "aidvantage",
      "edfinancial",
      "discover student",
      "sofi loan",
      "earnest loan",
      "personal loan",
      "debt",
    ],
    confidence: 0.9,
  },

  // Insurance (before housing — hoa could match "insurance")
  {
    category: "insurance",
    keywords: [
      "insurance",
      "geico",
      "state farm",
      "allstate",
      "progressive",
      "liberty mutual",
      "usaa",
      "nationwide",
      "farmers",
      "metlife",
      "aetna",
      "cigna",
      "blue cross",
      "bluecross",
      "anthem",
      "united health",
      "unitedhealthcare",
      "humana",
      "oscar health",
      "kaiser permanente",
      "hartford insurance",
      "travelers insurance",
      "chubb",
      "erie insurance",
      "lemonade insurance",
      "root insurance",
      "hippo insurance",
      "esurance",
      "21st century insurance",
      "safeco",
    ],
    confidence: 0.9,
  },

  // Subscriptions & streaming (before business_software so netflix etc. win)
  {
    category: "subscriptions",
    keywords: [
      "netflix",
      "spotify",
      "hulu",
      "disney+",
      "disney plus",
      "disneyplus",
      "apple music",
      "apple tv",
      "apple one",
      "youtube premium",
      "youtube music",
      "hbo max",
      "max.com",
      "paramount+",
      "paramount plus",
      "peacock",
      "peacocktv",
      "audible",
      "kindle unlimited",
      "amazon prime",
      "amazon music",
      "siriusxm",
      "pandora",
      "tidal",
      "deezer",
      "icloud",
      "google one",
      "google storage",
      "microsoft 365",
      "office 365",
      "xbox game pass",
      "playstation plus",
      "nintendo switch online",
      "crunchyroll",
      "funimation",
      "mubi",
      "criterion",
      "discovery+",
      "espn+",
      "fubo",
      "philo",
      "sling tv",
      "directv stream",
      "subscription",
      "substack",
      "patreon",
      "onlyfans",
      "masterclass",
    ],
    confidence: 0.9,
  },

  // Business software / SaaS
  {
    category: "business_software",
    keywords: [
      "github",
      "gitlab",
      "heroku",
      "aws ",
      "amazon web services",
      "google cloud",
      "gcp ",
      "azure ",
      "digitalocean",
      "vercel",
      "netlify",
      "render.com",
      "railway",
      "fly.io",
      "supabase",
      "planetscale",
      "neon.tech",
      "slack",
      "zoom",
      "notion",
      "figma",
      "jira",
      "atlassian",
      "confluence",
      "trello",
      "asana",
      "monday.com",
      "clickup",
      "linear.app",
      "basecamp",
      "airtable",
      "quickbooks",
      "freshbooks",
      "xero",
      "wave accounting",
      "bench accounting",
      "mailchimp",
      "sendgrid",
      "hubspot",
      "salesforce",
      "zendesk",
      "intercom",
      "squarespace",
      "shopify",
      "wix",
      "webflow",
      "godaddy",
      "namecheap",
      "cloudflare",
      "twilio",
      "stripe",
      "plaid",
      "docusign",
      "hellosign",
      "adobe acrobat",
      "adobe creative",
      "adobe sign",
      "canva",
      "loom",
      "calendly",
      "doodle",
      "1password",
      "lastpass",
      "dashlane",
      "gusto",
      "rippling",
      "deel",
      "remote.com",
      "bamboohr",
      "workday",
      "greenhouse",
      "lever.co",
      "dropbox business",
      "box.com",
    ],
    confidence: 0.85,
  },

  // Housing
  {
    category: "housing",
    keywords: [
      "rent",
      "mortgage",
      "hoa",
      "homeowner",
      "property tax",
      "landlord",
      "apartment",
      "realty",
      "real estate",
      "property management",
      "airbnb",
      "vrbo",
      "homeaway",
      "maintenance",
      "pest control",
      "lawn",
      "landscaping",
      "cleaning service",
      "maid",
      "home depot",
      "lowe's",
      "lowes",
      "ace hardware",
      "true value",
    ],
    confidence: 0.8,
  },

  // Utilities
  {
    category: "utilities",
    keywords: [
      "electric",
      "electricity",
      "water bill",
      "water dept",
      "water utility",
      "gas co",
      "gas company",
      "natural gas",
      "sewer",
      "utility",
      "utilities",
      "power",
      "energy",
      "pge",
      "pg&e",
      "con ed",
      "coned",
      "duke energy",
      "dominion energy",
      "southern company",
      "eversource",
      "national grid",
      "dte energy",
      "consumers energy",
      "we energies",
      "xcel energy",
      "entergy",
      "ameren",
      "peco",
      "pseg",
      "comcast",
      "xfinity",
      "spectrum",
      "cox ",
      "cox cable",
      "at&t",
      "att.com",
      "verizon",
      "t-mobile",
      "tmobile",
      "sprint",
      "boost mobile",
      "cricket wireless",
      "metro by t-mobile",
      "mint mobile",
      "visible wireless",
      "google fi",
      "internet",
      "broadband",
      "phone bill",
      "cell phone",
      "wireless bill",
      "dish network",
      "directv",
      "waste management",
      "republic services",
      "trash",
      "recycling",
    ],
    confidence: 0.85,
  },

  // Travel (before transportation/dining to catch airlines, hotels first)
  {
    category: "transportation",
    keywords: [
      "airline",
      "airways",
      "united airlines",
      "delta airlines",
      "american airlines",
      "southwest airlines",
      "jetblue",
      "alaska airlines",
      "spirit airlines",
      "frontier airlines",
      "lufthansa",
      "british airways",
      "air france",
      "emirates",
      "ryanair",
      "easyjet",
      "air canada",
      "westjet",
      "hotel",
      "marriott",
      "hilton",
      "hyatt",
      "ihg",
      "sheraton",
      "westin",
      "holiday inn",
      "best western",
      "radisson",
      "wyndham",
      "fairfield",
      "hampton inn",
      "doubletree",
      "motel 6",
      "extended stay",
      "travelodge",
      "days inn",
      "super 8",
      "comfort inn",
      "quality inn",
      "la quinta",
      "expedia",
      "booking.com",
      "hotels.com",
      "priceline",
      "kayak",
      "travelocity",
      "hotwire",
      "trivago",
      "orbitz",
      "amtrak",
      "greyhound",
      "megabus",
      "flixbus",
      "enterprise rent",
      "hertz",
      "avis",
      "budget car",
      "national car",
      "alamo",
      "thrifty car",
      "dollar rental",
      "zipcar",
      "turo",
      "gas station",
      "shell ",
      "exxon",
      "chevron",
      "bp ",
      "mobil",
      "citgo",
      "sunoco",
      "wawa",
      "speedway",
      "marathon gas",
      "casey's general",
      "kwik trip",
      "circle k",
      "7-eleven gas",
      "racetrac",
      "pilot flying j",
      "loves travel",
      "flying j",
      "fuel",
      "gasoline",
      "petrol",
      "uber",
      "lyft",
      "taxi",
      "cab ",
      "rideshare",
      "parking",
      "park & ride",
      "parkwhiz",
      "spothero",
      "toll",
      "e-zpass",
      "ezpass",
      "fastrak",
      "sunpass",
      "metro",
      "subway train",
      "bart ",
      "mta ",
      "transit",
      "bus pass",
      "train ticket",
      "car wash",
      "auto parts",
      "autozone",
      "o'reilly auto",
      "advance auto",
      "napa auto",
      "pep boys",
      "jiffy lube",
      "jiffy",
      "oil change",
      "valvoline",
      "tire",
      "firestone",
      "goodyear tire",
      "discount tire",
      "americas tire",
      "mavis discount",
      "midas",
      "meineke",
      "big o tire",
      "ntb tire",
      "christian brothers auto",
      "aamco",
      "auto repair",
      "brake",
      "mechanic",
      "dealership",
      "dmv",
      "motor vehicle",
      "vehicle registration",
    ],
    confidence: 0.8,
  },

  // Groceries
  {
    category: "groceries",
    keywords: [
      "whole foods",
      "trader joe",
      "trader joes",
      "kroger",
      "ralphs",
      "fry's food",
      "smith's food",
      "king soopers",
      "fred meyer",
      "qfc ",
      "harris teeter",
      "safeway",
      "publix",
      "aldi",
      "lidl",
      "costco",
      "sam's club",
      "sams club",
      "bj's wholesale",
      "bjs wholesale",
      "walmart supercenter",
      "walmart grocery",
      "grocery",
      "supermarket",
      "market basket",
      "food lion",
      "wegmans",
      "sprouts",
      "fresh market",
      "fresh thyme",
      "natural grocers",
      "h-e-b",
      "heb",
      "meijer",
      "giant food",
      "stop & shop",
      "stop and shop",
      "shop rite",
      "shoprite",
      "acme markets",
      "winn-dixie",
      "winndixie",
      "food 4 less",
      "food max",
      "smart & final",
      "stater bros",
      "price chopper",
      "hannaford",
      "iga supermarket",
      "piggly wiggly",
      "hy-vee",
      "jewel-osco",
      "dominick's",
      "randalls",
      "tom thumb",
      "vons",
      "pavilions",
      "albertsons",
      "lucky supermarket",
      "save mart",
      "raley's",
      "winco foods",
      "dillons",
    ],
    confidence: 0.85,
  },

  // Dining
  {
    category: "dining",
    keywords: [
      "restaurant",
      "chipotle",
      "mcdonald",
      "mcdonalds",
      "mcd ",
      "starbucks",
      "sbux",
      "dunkin",
      "dunkin donuts",
      "subway sandwich",
      "domino",
      "pizza hut",
      "papa john",
      "little caesar",
      "pizza",
      "burger king",
      "burger",
      "taco bell",
      "wendy",
      "chick-fil-a",
      "chickfila",
      "panera",
      "grubhub",
      "doordash",
      "ubereats",
      "uber eats",
      "postmates",
      "instacart",
      "drizly",
      "seamless",
      "caviar food",
      "cafe",
      "coffee",
      "diner",
      "grill ",
      "kitchen",
      "bakery",
      "sushi",
      "thai food",
      "chinese food",
      "indian food",
      "pho",
      "ramen",
      "chili's",
      "olive garden",
      "outback steakhouse",
      "applebees",
      "tgi friday",
      "ihop",
      "waffle house",
      "denny's",
      "red lobster",
      "longhorn steakhouse",
      "texas roadhouse",
      "five guys",
      "shake shack",
      "in-n-out",
      "in n out",
      "whataburger",
      "sonic drive",
      "jack in the box",
      "del taco",
      "qdoba",
      "popeyes",
      "church's chicken",
      "kfc ",
      "kentucky fried",
      "raising cane",
      "zaxby",
      "wingstop",
      "buffalo wild",
      "jersey mike",
      "jimmy john",
      "firehouse sub",
      "potbelly",
      "jason's deli",
      "which wich",
      "moe's southwest",
      "habit burger",
      "toast tab",
      "toasttab",
      "olo.com",
      "eat ",
      "snack",
      "bar & grill",
      "pub ",
      "tavern",
      "bistro",
      "brasserie",
      "trattoria",
      "cantina",
      "taproom",
      "brew pub",
      "bbq",
      "barbeque",
      "steakhouse",
      "seafood",
      "wings",
      "noodle",
      "taqueria",
      "burrito",
      "wrap",
      "smoothie",
      "juice bar",
      "boba",
      "donut",
      "bagel",
      "deli",
      "sandwich",
      "sub shop",
      "catering",
    ],
    confidence: 0.8,
  },

  // Health & Medical
  {
    category: "health",
    keywords: [
      "pharmacy",
      "cvs",
      "walgreens",
      "rite aid",
      "riteaid",
      "duane reade",
      "health mart",
      "medicine shoppe",
      "doctor",
      "physician",
      "medical",
      "hospital",
      "dental",
      "dentist",
      "orthodont",
      "optometry",
      "optometrist",
      "vision care",
      "lenscrafters",
      "america's best",
      "visionworks",
      "urgent care",
      "clinic",
      "labcorp",
      "lab corp",
      "quest diagnostics",
      "questdiagnostics",
      "planned parenthood",
      "therapy",
      "therapist",
      "counseling",
      "psychiatry",
      "psychology",
      "mental health",
      "talkspace",
      "betterhelp",
      "cerebral health",
      "noom",
      "weight watcher",
      "nutrisystem",
      "gym",
      "fitness",
      "planet fitness",
      "la fitness",
      "24 hour fitness",
      "lifetime fitness",
      "anytime fitness",
      "equinox",
      "crunch fitness",
      "blink fitness",
      "blink gym",
      "blink ",
      "ymca",
      "crossfit",
      "orangetheory",
      "pure barre",
      "soulcycle",
      "peloton",
      "pilates",
      "yoga",
      "massage",
      "chiropractor",
      "physical therapy",
      "rehabilitation",
      "lab work",
      "blood test",
      "x-ray",
      "radiology",
      "surgery",
      "anesthesia",
      "copay",
      "co-pay",
      "prescription",
      "rx",
      "vitamin",
      "supplement",
      "gnc",
      "vitamin shoppe",
      "natural health",
      "health food",
      "healthcare",
    ],
    confidence: 0.8,
  },

  // Online education subscriptions
  {
    category: "subscriptions",
    keywords: [
      "coursera",
      "udemy",
      "skillshare",
      "linkedin learning",
      "pluralsight",
      "datacamp",
      "codecademy",
      "treehouse",
      "udacity",
      "khan academy",
      "chegg",
      "course hero",
      "quizlet",
      "masterclass",
      "brilliant.org",
      "duolingo",
    ],
    confidence: 0.82,
  },
  // Physical education / institution expenses
  {
    category: "shopping",
    keywords: [
      "tuition",
      "university",
      "college",
      "school fees",
      "textbook",
      "bookstore",
      "student fee",
      "enrollment fee",
      "campus",
    ],
    confidence: 0.72,
  },

  // Childcare / family services
  {
    category: "shopping",
    keywords: [
      "daycare",
      "day care",
      "childcare",
      "child care",
      "babysitter",
      "nanny",
      "au pair",
      "preschool",
      "nursery school",
      "after school",
      "summer camp",
      "bright horizons",
      "kindercare",
      "learning care",
    ],
    confidence: 0.78,
  },

  // Charity / donations
  {
    category: "shopping",
    keywords: [
      "donation",
      "donate",
      "charity",
      "charitable",
      "nonprofit",
      "non-profit",
      "gofundme",
      "patreon",
      "united way",
      "red cross",
      "salvation army",
      "goodwill",
      "habitat for humanity",
      "oxfam",
      "doctors without borders",
      "msf usa",
      "unicef",
      "planned parenthood",
      "aclu",
    ],
    confidence: 0.68,
  },

  // Fees
  {
    category: "fees",
    keywords: [
      "fee",
      "overdraft",
      "nsf",
      "non-sufficient",
      "insufficient fund",
      "late charge",
      "late fee",
      "service charge",
      "annual fee",
      "maintenance fee",
      "monthly fee",
      "account fee",
      "atm fee",
      "wire fee",
      "foreign transaction",
      "currency conversion",
      "cash advance fee",
      "returned check",
      "stop payment",
      "penalty",
      "fine ",
      "bank charge",
    ],
    confidence: 0.9,
  },

  // Entertainment
  {
    category: "entertainment",
    keywords: [
      "theatre",
      "theater",
      "amc ",
      "regal cinema",
      "cinemark",
      "concert",
      "ticketmaster",
      "stubhub",
      "seatgeek",
      "vivid seats",
      "eventbrite",
      "bowling",
      "arcade",
      "museum",
      "zoo ",
      "aquarium",
      "amusement park",
      "six flags",
      "cedar point",
      "universal studios",
      "disney world",
      "disneyland",
      "seaworld",
      "steam game",
      "steam purchase",
      "playstation store",
      "psn ",
      "xbox store",
      "nintendo eshop",
      "epic games",
      "riot games",
      "blizzard",
      "activision",
      "ea sports",
      "ubisoft",
      "2k games",
      "humble bundle",
      "twitch ",
      "golf",
      "mini golf",
      "go-kart",
      "escape room",
      "laser tag",
      "trampoline",
      "paintball",
      "rock climbing",
      "comedy club",
      "improv",
      "nightclub",
      "club cover",
      "bar tab",
      "karaoke",
      "billiards",
      "pool hall",
    ],
    confidence: 0.75,
  },

  // Shopping (broad — keep near end so specific merchants match first)
  {
    category: "shopping",
    keywords: [
      "amazon",
      "amzn",
      "walmart ",
      "best buy",
      "ikea",
      "etsy",
      "ebay",
      "apple store",
      "apple.com",
      "nike",
      "adidas",
      "nordstrom",
      "macy",
      "tj maxx",
      "tjmaxx",
      "marshalls",
      "ross stores",
      "old navy",
      "gap ",
      "banana republic",
      "zara",
      "h&m",
      "uniqlo",
      "forever 21",
      "express clothing",
      "victoria's secret",
      "bath & body",
      "bed bath",
      "williams sonoma",
      "pottery barn",
      "west elm",
      "restoration hardware",
      "pier 1",
      "tuesday morning",
      "five below",
      "dollar tree",
      "dollar general",
      "family dollar",
      "big lots",
      "kohls",
      "jcpenney",
      "sears",
      "jcp",
      "newegg",
      "b&h photo",
      "bhphotovideo",
      "micro center",
      "fry's electronics",
      "staples",
      "office depot",
      "officemax",
      "container store",
      "world market",
      "crate & barrel",
      "target ",
      "petco",
      "petsmart",
      "chewy",
      "petco",
      "tractor supply",
      "cabela",
      "bass pro",
      "rei ",
      "dick's sporting",
      "academy sports",
      "modell's",
      "sport chalet",
      "foot locker",
      "finish line",
      "journeys",
      "dsw ",
      "payless",
      "shoe carnival",
      "famous footwear",
      "skechers",
      "ugg ",
      "lululemon",
      "athleta",
      "under armour",
      "columbia sportswear",
      "the north face",
      "patagonia",
      "michaels store",
      "hobby lobby",
      "joann fabric",
      "craft",
      "thrift",
      "shop.com",
      "overstock",
      "wayfair",
      "wish.com",
      "temu",
      "shein",
      "aliexpress",
      "alibaba",
      "romwe",
      "zaful",
      "fashion nova",
      "pretty little thing",
      "boohoo",
      "revolve",
      "asos",
      "urban outfitters",
      "anthropologie",
      "free people",
      "depop",
      "poshmark",
      "mercari",
      "thredup",
      "costco.com",
      "samsclub",
      "sam's club",
      "bjs wholesale",
      "storenvy",
    ],
    confidence: 0.7,
  },
];

/** Merchants that strongly suggest a recurring charge. */
const RECURRING_KEYWORDS = [
  "netflix",
  "spotify",
  "hulu",
  "disney",
  "hbo",
  "max.com",
  "paramount",
  "peacock",
  "peacocktv",
  "audible",
  "apple music",
  "apple tv",
  "apple one",
  "youtube premium",
  "amazon prime",
  "amazon music",
  "siriusxm",
  "pandora",
  "tidal",
  "adobe",
  "microsoft 365",
  "office 365",
  "icloud",
  "google one",
  "google storage",
  "dropbox",
  "github",
  "gitlab",
  "slack",
  "zoom",
  "notion",
  "figma",
  "mailchimp",
  "hubspot",
  "quickbooks",
  "freshbooks",
  "shopify",
  "squarespace",
  "insurance",
  "geico",
  "state farm",
  "allstate",
  "progressive",
  "rent",
  "mortgage",
  "gym",
  "planet fitness",
  "la fitness",
  "24 hour fitness",
  "anytime fitness",
  "equinox",
  "orangetheory",
  "peloton",
  "ymca",
  "subscription",
  "monthly",
  "annual fee",
  "patreon",
  "substack",
  "crunchyroll",
  "discovery+",
  "espn+",
  "fubo",
  "sling tv",
  "masterclass",
  "sallie mae",
  "navient",
  "navient",
  "comcast",
  "xfinity",
  "spectrum",
  "at&t",
  "verizon",
  "t-mobile",
];

const NON_EXPENSE_CATEGORIES: ReadonlySet<string> = new Set(["transfers", "income", "other"]);

const EXPENSE_CATEGORIES: ReadonlySet<string> = new Set(
  CATEGORY_RULES.map((r) => r.category).filter((c) => !NON_EXPENSE_CATEGORIES.has(c)),
);

const REFUND_KEYWORDS = ["refund", "return credit", "credit adj", "reversal", "chargeback", "adjustment cr"];

function matchesAny(merchant: string, keywords: string[]): boolean {
  const lower = merchant.toLowerCase();
  return keywords.some((kw) => lower.includes(kw));
}

export function classifyTransaction(
  merchant: string,
  amount: number,
  flowType: "inflow" | "outflow",
): ClassificationResult {
  const lower = merchant.toLowerCase();

  // Step 1: Always run keyword matching first
  let category: V1Category = "other";
  let confidence = 0.3;
  let matchedKeyword = "";

  for (const rule of CATEGORY_RULES) {
    for (const kw of rule.keywords) {
      if (lower.includes(kw)) {
        category = rule.category;
        confidence = rule.confidence;
        matchedKeyword = kw;
        break;
      }
    }
    if (matchedKeyword) break;
  }

  // Step 2: Determine transaction class, respecting keyword results
  let transactionClass: ClassificationResult["transactionClass"];
  let flowOverride: "outflow" | null = null;

  if (matchesAny(merchant, REFUND_KEYWORDS) && flowType === "inflow") {
    transactionClass = "refund";
  } else if (matchesAny(merchant, TRANSFER_KEYWORDS)) {
    transactionClass = "transfer";
    if (!matchedKeyword) {
      category = "transfers";
      confidence = 0.8;
      matchedKeyword = "transfer";
    }
  } else if (matchedKeyword && EXPENSE_CATEGORIES.has(category)) {
    transactionClass = "expense";
    if (flowType === "inflow") {
      flowOverride = "outflow";
    }
  } else if (flowType === "inflow") {
    transactionClass = "income";
    if (!matchedKeyword) {
      category = "income";
      confidence = 0.8;
      matchedKeyword = "inflow";
    }
  } else {
    transactionClass = "expense";
  }

  // Step 3: Recurrence hint
  const recurrenceType = matchesAny(merchant, RECURRING_KEYWORDS)
    ? "recurring" as const
    : "one-time" as const;

  const labelReason = matchedKeyword
    ? `Matched keyword "${matchedKeyword}" → ${category}`
    : `No keyword match — defaulted to ${category}`;

  return {
    transactionClass,
    category,
    recurrenceType,
    labelSource: "rule",
    labelConfidence: confidence,
    labelReason,
    flowOverride,
  };
}
